name: Run get.py

on:
  workflow_dispatch:

jobs:
  run-get-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tenacity

    - name: Run get.py script
      run: python get.py
    
    - name: Push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'zander@zanderlewis.dev'
        git add .
        git commit -m "Update data"
        git push origin main
